version: '3.2'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'tap_obscore'
    volumes:
      - './proxy/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on: 
      - 'tap_obscore'
  tap_obscore:
    image: opencadc/alma-tap:1.0.0
    #build: ./
    depends_on:
      - 'tapdb'
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'tap_obscore'
    environment: 
      CATALINA_OPTS: "-Dtapuser.jdbc.username=TAP_SCHEMA -Domit-alma-test=true -Dtapuser.jdbc.password=TAP_SCHEMA -Dtapuser.jdbc.driverClassName=oracle.jdbc.OracleDriver -Dtapuser.jdbc.url=jdbc:oracle:thin:@tapdb:1521/XE -Dca.nrc.cadc.reg.client.RegistryClient.local=true"
  tapdb:
    image: opencadc/tap-oracle:11-xe
    shm_size: 1gb
    networks:
      - 'tap_obscore'
    volumes:
      - './sql:/docker-entrypoint-initdb.d/startup'

networks:
  tap_obscore:
